### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by rssdevoloper** [taufikdev88/simplewhatsappapi#4]
Error mas ketika saya coba scan qr di wa versi 2.22.14.74

App crash

**Comment by taufikdev88** [comment]
Boleh lampirkan error message nya ?

**Comment by doko89** [comment]
ini mas saya bantu post error nya
`Sending To: 085xxxxxxxx with message: hallo test kirim pesan
Formatted jid to: 6285xxxxxxxxx@s.whatsapp.net
/app/services/WhatsappService.js:114
            yield this.sock.presenceSubscribe(jid);
                            ^

TypeError: this.sock.presenceSubscribe is not a function
    at WhatsappService.<anonymous> (/app/services/WhatsappService.js:114:29)
    at Generator.next (<anonymous>)
    at /app/services/WhatsappService.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/app/services/WhatsappService.js:27:12)
    at WhatsappService.SendWhatsappSimpleMessage (/app/services/WhatsappService.js:110:16)
    at /app/index.js:56:16
    at /app/helper/Validator.js:10:29
    at AsyncResolvers.resolvedAll [as onResolvedAll] (/app/node_modules/validatorjs/src/validator.js:103:9)
    at AsyncResolvers.fire (/app/node_modules/validatorjs/src/async.js:65:12)
`

**Comment by taufikdev88** [comment]
update ke aplikasi wa terbaru ya
